GET http://localhost:3001/api/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/api/persons/1

###

GET http://localhost:3001/api/persons/doesntexist

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-243563"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen",
    "number": "040-2435"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test Person",
    "number": "000-00000"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "39-44-5323523"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Test Person"
}
###

DELETE http://localhost:3001/api/persons/2

###

PUT http://localhost:3001/api/persons/60cd9db4ec358631f0125fd3
Content-Type: application/json

{
    "name": "Test Person",
    "number": "333-3333"
}